std_name=str(input("Enter your name: "))
En_no=str(input("Enter your EN. No.:"))
course=str(input("Enter your course:"))
clg_name=str(input("Enter your college name:"))
print("Hello ",std_name)
print("Enrollment Number:",En_no)
print("course:",course)
print("college name:",clg_name)
